apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jenkins-agent-deployment.yaml
  - github-runner-deployment.yaml
  - gitlab-runner-deployment.yaml
  - gitlab-runner-rbac.yaml
